### ISSUE TITLE
Errors noticed while writing integration test checklist.

### ISSUE THREAD

**Issue by pmanko** [myapnea/www.myapnea.org#302]
Noticed while working on #235.

- [x] `Enter` key form submission does not seem to happen on some forms like sign in and registration. There might be a global javascript event handler that prevents this default action.
- [x] Invalid authenticity token errors pop up occasionally. I wasn't able to pinpoint the exact instances.
- [x] Something doesn't seem to work correctly with the Registration error handling. I kept getting `Email already taken` errors, even though I had no confirmation of registration going through.
- [x] `part_of_registration` variable in beta consent seems to not always be set? I got this error when attempting to fill out surveys with a user that had not signed the consent yet.
- [x] In surveys, focus incorrectly switches to any nested input box when the parent question is selected.
- [x] No survey information or survey title is visible in `show` view
- #358 Change error message for `over 18` checkbox not being selected.
- [x] Discuss whether specific year required, or just a checkbox confirming age >= 18. Right now, the year validation might miss 18 +/- 11 months.
  - [x] Change this to checkbox - frontend
  - [x] Change this to checkbox - backend
- [x] On get-started path, blank submission of user_role should return with an error asking users to choose at least one user_role
- [x] On get-started path, declining privacy policy should redirect to home page, with no negative flash alert
- [x] On get-started path, declining consent should redirect to home page, with no negative flash alert
- [x] Text at end of privacy policy and consent should reflect wording of respective 'accept' button 
- #359  Make surveys responsive to numpad hotkeys
- [x] Provider welcome message should highlight existing default value on focus
- [x] Add validation on provider profile step of get-started path for new providers, explaining why they should fill out the information
- [x] Provider profile's custom url should be auto-populated when official provider name loses focus (highlight auto-populated value)
- [x] Provider should be redirected to their actual provider page upon submission of provider profile
- [x] Ensure that all pages receive at least the default page_title for SEO
- [x] Refactor the static controller and views to move non-static pages to proper locations.
I'll keep adding to this issue as I work on the checklist.
- [x] When users go to surveys and don't have signed consent or privacy policy, they are redirected correctly to privacy policy/consent. However, after this process if finished, they are redirected to account page. Redirect should be friendly.
- [x] In consent/privacy policy flow, friendly forwarding and friendly returning should be set up
  - [x] Privacy policy should forward to consent, return to previous location
  - [x] Consent should forward to survey or survey index, return to previous location
  - #360  Buttons on account page should indicate status of acceptance for both items
- [x] Determine frequency of voting - **finalize** ----- moved to #310 
- [x] Add new research topic needs to have validation before submitting
- [x] Messaging needs to be displayed to explain the approval process once user adds a new research topic
- [x] Survey page should have a `Save and Exit` type button clearly available which redirects to survey index page. --> Survey introduction should clearly explain that users can leave at any point.
- [x] Survey page should include a `Submit Survey` type button which submits a survey, locks answered questions, and shows survey report or continues to next survey.
- [x] Survey index and home dashboard survey section should allow users to answer unanswered questions.
- [x] Remove beta alerts and cookies
- [x] Bump up the Recent News secton on right nav
- [x] Forums should scale more dynamically
- [x] Forum action buttons on mobile devices currently look disabled - change for consistency
- [x] Forums (on index page) should have pagination
- [x] Check consistency of paragraph sizes for responsive design across site
- [x] Researcher should have path separate from providers and other users, should currently contain at least terms of access

**Comment by krand7** [comment]
@pmanko do you think a save and exit button is necessary? With the single page flow and extreme change in length, I'm not sure this will add a ton, and will require some relatively complex positioning to look natural. Just a thought!

Also, I think we should stay away from a submit survey button, and rather have the 'Congratulations' message appear after the user progresses past the last question. This way, we can encourage them to complete other surveys, and make the show report a secondary option (based on discussions with @ekontos ). Let me know your thoughts here!

**Comment by pmanko** [comment]
@krand7 @ekontos @remomueller I agree that keeping the flow as simple as possible is important. However, I think users should somehow be assured that their answers are getting saved, and that they can leave surveys without losing any work. There's no point in displaying survey progress otherwise, but we can definitely be flexible with how we do it.

In terms of the submit survey button, I also like the direct flow into other surveys. However, we've also had discussions about locking survey questions once they are completed. In addition, we're gearing toward allowing users to go back and complete questions that they might have skipped, while preventing them from modifying questions they have already answered. See issue #298 . 

Whatever the mechanism is, we have to have a trigger for when we mark completed answers as completed and unanswered questions as skipped.

**Comment by krand7** [comment]
@pmanko Okay that all sounds logical, maybe we can focus on this tomorrow? Sounds like it will need a bit more of an involved conversation to finalize the best solution for all of these points.

**Comment by ekontos** [comment]
Let's discuss. Another related item we discussed was not allowing survey progress without an answer. HeH does this. There are pluses and minuses.

On Feb 11, 2015, at 8:02 PM, "Kyle Rand" <notifications@github.com<mailto:notifications@github.com>> wrote:


@pmanko<https://github.com/pmanko> Okay that all sounds logical, maybe we can focus on this tomorrow? Sounds like it will need a bit more of an involved conversation to finalize the best solution for all of these points.

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/302#issuecomment-73998506>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by remomueller** [comment]
I wouldn't prevent progression without an answer. Validations can be frustrating to users, and I can see them stopping altogether. I would suggest that surveys that are incomplete are just left as such, and that users get notified that incomplete surveys don't receive a lottery ticket, or something along those lines. We don't want to interrupt any flow in filling out surveys by making them jump back to a question they may have intentionally skipped and left blank.
